version: '3.9'
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-net

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.17.10
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    ports:
      - 5601:5601

volumes:
  esdata:

networks:
  es-net:
    driver: bridge
